openapi: 3.0.0
servers: []
info:
  description: Sos API contains information about Spain's 2016 general elections results.
  contact:
    name: Ignacio Peluaga
    email: ipeluaga@gmail.com
    #url: 'https://github.com/ignpelloz'
  license:
    name: MIT Liscense
    #url: 'http://opensource.org/licenses/MIT'
  version: 1.0.0
  title: 'G05: Elections Voting Stats'
paths:
  /api/v3/elections-voting-stats:
    get:
      parameters:
        - name: apikey
          in: query
          description: Apikey needed to execute any action
          required: true
          schema:
            type: string
      tags:
        - API actions
      summary: Get the whole data collection
      description: >-
        By aplying a GET request to this path, you will obtain the whole
        elections results data
      operationId: getResults
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/result'
        '500':
          description: Error getting data from DB
    post:
      tags:
        - API actions
      summary: Add a new elections result
      description: Use this method to add a new resource
      operationId: addResults
      parameters:
        - name: apikey
          in: query
          description: Apikey needed to execute any action
          required: true
          schema:
            type: string
      responses:
        '201':
          description: successful operation
        '400':
          description: No resource to add was specified
        '409':
          description: Resource to add already exists
        '422':
          description: Resource to add is not well formed
        '500':
          description: Error getting data from DB
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/result'
        description: Results object that needs to be added to data base
        required: true
    delete:
      parameters:
        - name: apikey
          in: query
          description: Apikey needed to execute any action
          required: true
          schema:
            type: string
      tags:
        - API actions
      summary: Delete the whole DB
      description: By executing this method you will delete the whole DB
      operationId: deleteAll
      responses:
        '204':
          description: Succesful action
        '404':
          description: There are no voting results to delete
        '500':
          description: Error removing data from DB
  '/api/v3/elections-voting-stats/{province}':
    get:
      tags:
        - API actions
      summary: Find results by indicating the province
      description: >-
        Using this method you will get the elections results for a specified
        province
      operationId: getSingleResults
      parameters:
        - name: apikey
          in: query
          description: Apikey needed to execute any action
          required: true
          schema:
            type: string
        - name: province
          in: path
          description: Province whose elections results are desired
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/result'
        '400':
          description: No province was specified
        '404':
          description: There aren't voting results for the specified province
        '500':
          description: Error getting data from DB
    put:
      tags:
        - API actions
      summary: Update results of a specified province
      description: >-
        By using this method you will be able to update the resource for a
        specified province
      operationId: updateResults
      parameters:
        - name: apikey
          in: query
          description: Apikey needed to execute any action
          required: true
          schema:
            type: string
        - in: path
          name: province
          description: Province whose results need to be updated
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Request without province or with different ID's
        '404':
          description: There aren't voting results for the specified province
        '422':
          description: Resource to add is not well formed
        '500':
          description: Error getting data from DB
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/result'
        description: Results object that will update the existing one in the data base
        required: true
    delete:
      tags:
        - API actions
      summary: Delete the elections results for a specified province
      description: >-
        Using this method you will be able to delete the elections results for a
        specified province
      operationId: deleteSingleResource
      parameters:
        - name: apikey
          in: query
          description: Apikey needed to execute any action
          required: true
          schema:
            type: string
        - name: province
          in: path
          description: Province whose results have got to be deleted
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Succesful action
        '400':
          description: No province was specified
        '404':
          description: There are no voting results to delete for the specified province
        '500':
          description: Error removing data from DB
components:
  schemas:
    result:
      type: object
      properties:
        province:
          type: string
        year:
          type: integer
          format: int32
        pp:
          type: integer
          format: int32
        podemos:
          type: integer
          format: int32
        psoe:
          type: integer
          format: int32
        cs:
          type: integer
          format: int32
